# Enable language support
language: fortran

# Compiler list
compiler:
    - gfortran

os:
    - osx


before_install:
    - brew update
    - brew install gcc5
    - brew tap homebrew/science
    - brew install hdf5 --with-fortran --with-fortran2003



# Build
script:
    - mkdir build
    - cd build
    - cmake .. && make
