# Enable language support
language: fortran

# Compiler list
compiler:
    - gfortran

os:
    - osx




matrix:
    include:
        -os: osx
            compiler = gfortran
        -before_install:
            - brew update
            - brew tap homebrew/science
            - brew install hdf5 --with-fortran --with-fortran2003
            - brew uninstall gcc
            - brew install gcc5
        -os: osx
            compiler = gfortran
        -before_install:
            - brew update
            - brew tap homebrew/science
            - brew install hdf5 --with-fortran --with-fortran2003
            - brew uninstall gcc
            - brew install gcc6
            

#before_install:
#    - brew update
#    - brew tap homebrew/science
#    - brew install hdf5 --with-fortran --with-fortran2003
#    - brew uninstall gcc
#    - brew install gcc5



# Build
script:
    - mkdir build
    - cd build
    - cmake .. && make
