# Enable language support
language: fortran

# Compiler list
compiler:
    - gfortran-4
    - gfortran-5

os:
    - osx


before_install:
    - brew update
    - brew unlink cmake
    - brew install cmake
    - brew tap homebrew/science
    - brew install hdf5



# Build
script:
    - mkdir build
    - cd build
    - cmake .. && make
