# Enable language support
language: fortran

# Compiler list
compiler:
    - gfortran

os:
    - osx


before_install:
    - brew update
    - brew unlink cmake
    - brew install cmake 3.5
    - brew tap homebrew/science
    - brew install hdf5



# Build
script:
    - mkdir build
    - cd build
    - cmake .. && make
